version: "3.8"

services:
  mcp-adapter:
    build: .
    container_name: mcp-adapter
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app

  celery-worker:
    build: .
    container_name: mcp-celery
    command: celery -A celery_worker.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7
    container_name: mcp-redis
    ports:
      - "6379:6379"
